Repository debrajhyper/Topic_Learning_Resources, pull requests merged in 2022-10, with the labels that each got.

#106 Added Resorces For Competitive Programming
  README.md
Labels: Hacktoberfest2022

#132 Add DSA, HTML and CSS resources
  README.md
Labels: Hacktoberfest2022

#131 Add Css Diner
  CONTRIBUTING.md
Labels: Hacktoberfest2022

#119 added code of conduct
  CODE_OF_CONDUCT.md
Labels: Hacktoberfest2022

#144 Added 8 Resources on OOPS, Git, STL, DBMS, Angular JS and Django Data Structures.
  README.md
Labels: Hacktoberfest2022

#143 Update README.md
  README.md
Labels: Hacktoberfest2022

#142 Angular Course For Beginners
  CONTRIBUTING.md
Labels: Hacktoberfest2022

#141 Add 2 GoLang Doc links to README.md
  README.md
Labels: Hacktoberfest2022

#140 Added Perl Documentation
  README.md
Labels: Hacktoberfest2022

#138 Update README.md
  README.md
Labels: Hacktoberfest2022

#122 feat: add github for grpc course
  README.md
Labels: Hacktoberfest2022

#121 Added a book for competitive programming
  README.md
Labels: Hacktoberfest2022

#96 Added CSS video
  README.md
Labels: Hacktoberfest2022

#64 added android dev resource.Hope this helps ❤️
  README.md
Labels: Hacktoberfest2022

#155 Added Data Science and Machine Learning Video Tutorials
  CONTRIBUTING.md
Labels: Hacktoberfest2022

#153 add golang docs
  README.md
Labels: Hacktoberfest2022

#168 added document on SQL
  README.md
Labels: Hacktoberfest2022

#169 added document on SASS
  README.md
Labels: Hacktoberfest2022

#170 Blockchain Development Content Added
  README.md
Labels: Hacktoberfest2022

#151 Updated README
  README.md
Labels: Hacktoberfest2022

#103 Backend Development Resources added
  README.md
Labels: good first issue, Hacktoberfest2022

#102 add reactjs resource
  README.md
Labels: help wanted, Hacktoberfest2022

#72 Added Node, express and full stack course
  README.md
Labels: help wanted, Hacktoberfest2022

#101 Update README.md
  README.md
Labels: help wanted, Hacktoberfest2022

#154 added resources
  README.md
Labels: duplicate, Hacktoberfest2022

#76 Added Kotlin Programming language offical docs
  README.md
Labels: help wanted, Hacktoberfest2022

#104 Added one Video Resource for Frontend Web Development
  README.md
Labels: help wanted, Hacktoberfest2022

#182 Add resources vue.js
  README.md
Labels: Hacktoberfest2022

#195 Update documentations part for cleaner access.
  README.md
Labels: Hacktoberfest2022

#73 Added The Odin project in HTML/CSS and Javascript section.
  README.md
Labels: help wanted, Hacktoberfest2022

#192 Add JS MDN Web docs
  README.md
Labels: help wanted, Hacktoberfest2022

#187 Backend Resources Added (Golang)
  README.md
Labels: help wanted, Hacktoberfest2022

#205 Updated README.md
  README.md
Labels: Hacktoberfest2022

#222 added next js in frontend playlist section
  README.md
Labels: Hacktoberfest2022

#219 Added Flutter Resources
  README.md
Labels: Hacktoberfest2022

#216 Add Python (Beginner + OOPS) Video Resource
  README.md
Labels: Hacktoberfest2022

#206 Add devops/ aws resources
  README.md
Labels: Hacktoberfest2022
